### ISSUE TITLE
Unnecessary driver modification

### ISSUE THREAD

**Issue by Razi91** [JON95Git/lvgl-nrf52840-mdk-sample#1]
Just add `spi-cpol` to device tree

**Comment by JON95Git** [comment]
This uses a very old Zephyr version. You can try the latest driver using the current Zephyr.

**Comment by Razi91** [comment]
I just did it on the latest zephyr version, adding this flag solves the problem with frequencies higher than 2MHz, somehow for 2MHz it works without that modification.

**Comment by JON95Git** [comment]
Ok. Glad to know it worked for you. Thanks for letting me know.

**Comment by Razi91** [comment]
Okay, I just confirmed that it works on both nRF52840 (using Seeed Xiao, even at 32MHz) and RPi Pico
